
version: "3"

services:
    mongo:
      image: mongo
      restart: always
      ports:
        - 27016:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: s3cr37



    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: s3cr37


    mysql:
      image: mysql:latest
      container_name: "MySQL_DB"
      ports:
        - "33007:3306"
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_ROOT_PASSWORD: s3cr37
        MYSQL_DATABASE: quiz_user
